/*! \file exif-tag.h
 *  \brief Handling EXIF tags
 */
/*
 * Copyright (c) 2001 Lutz Mueller <lutz@users.sourceforge.net>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details. 
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA.
 */

#ifndef LIBEXIF_EXIF_TAG_H
#define LIBEXIF_EXIF_TAG_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <libexif/exif-ifd.h>
#include <libexif/exif-data-type.h>

/*! EXIF tags */
typedef enum {
  EXIF_TAG_INTEROPERABILITY_INDEX = 0x0001,
  EXIF_TAG_INTEROPERABILITY_VERSION = 0x0002,
  EXIF_TAG_PROCESSING_SOFTWARE = 0x000b,
  EXIF_TAG_NEW_SUBFILE_TYPE = 0x00fe,
  EXIF_TAG_SUBFILE_TYPE = 0x00ff,
  EXIF_TAG_IMAGE_WIDTH = 0x0100,
  EXIF_TAG_IMAGE_LENGTH = 0x0101,
  EXIF_TAG_BITS_PER_SAMPLE = 0x0102,
  EXIF_TAG_COMPRESSION = 0x0103,
  EXIF_TAG_PHOTOMETRIC_INTERPRETATION = 0x0106,
  EXIF_TAG_THRESHOLDING = 0x0107,
  EXIF_TAG_CELL_WIDTH = 0x0108,
  EXIF_TAG_CELL_LENGTH = 0x0109,
  EXIF_TAG_FILL_ORDER = 0x010a,
  EXIF_TAG_DOCUMENT_NAME = 0x010d,
  EXIF_TAG_IMAGE_DESCRIPTION = 0x010e,
  EXIF_TAG_MAKE = 0x010f,
  EXIF_TAG_MODEL = 0x0110,
  EXIF_TAG_STRIP_OFFSETS = 0x0111,
  EXIF_TAG_ORIENTATION = 0x0112,
  EXIF_TAG_SAMPLES_PER_PIXEL = 0x0115,
  EXIF_TAG_ROWS_PER_STRIP = 0x0116,
  EXIF_TAG_STRIP_BYTE_COUNTS = 0x0117,
  EXIF_TAG_MIN_SAMPLE_VALUE = 0x0118,
  EXIF_TAG_MAX_SAMPLE_VALUE = 0x0119,
  EXIF_TAG_X_RESOLUTION = 0x011a,
  EXIF_TAG_Y_RESOLUTION = 0x011b,
  EXIF_TAG_PLANAR_CONFIGURATION = 0x011c,
  EXIF_TAG_PAGE_NAME = 0x011d,
  EXIF_TAG_X_POSITION = 0x011e,
  EXIF_TAG_Y_POSITION = 0x011f,
  EXIF_TAG_FREE_OFFSETS = 0x0120,
  EXIF_TAG_FREE_BYTE_COUNTS = 0x0121,
  EXIF_TAG_GRAY_RESPONSE_UNIT = 0x0122,
  EXIF_TAG_GRAY_RESPONSE_CURVE = 0x0123,
  EXIF_TAG_T4_OPTIONS = 0x0124,
  EXIF_TAG_T6_OPTIONS = 0x0125,
  EXIF_TAG_RESOLUTION_UNIT = 0x0128,
  EXIF_TAG_TRANSFER_FUNCTION = 0x012d,
  EXIF_TAG_SOFTWARE = 0x0131,
  EXIF_TAG_DATE_TIME = 0x0132,
  EXIF_TAG_ARTIST = 0x013b,
  EXIF_TAG_HOST_COMPUTER = 0x013c,
  EXIF_TAG_PREDICTOR = 0x013d,
  EXIF_TAG_WHITE_POINT = 0x013e,
  EXIF_TAG_PRIMARY_CHROMATICITIES = 0x013f,
  EXIF_TAG_COLOR_MAP = 0x0140,
  EXIF_TAG_HALFTONE_HINTS = 0x0141,
  EXIF_TAG_TILE_WIDTH = 0x0142,
  EXIF_TAG_TILE_LENGTH = 0x0143,
  EXIF_TAG_TILE_OFFSETS = 0x0144,
  EXIF_TAG_TILE_BYTE_COUNTS = 0x0145,
  EXIF_TAG_BAD_FAX_LINES = 0x0146,
  EXIF_TAG_CLEAN_FAX_DATA = 0x0147,
  EXIF_TAG_CONSECUTIVE_BAD_FAX_LINES = 0x0148,
  EXIF_TAG_SUB_IFDS = 0x014a,
  EXIF_TAG_INK_SET = 0x014c,
  EXIF_TAG_INK_NAMES = 0x014d,
  EXIF_TAG_NUMBER_OF_INKS = 0x014e,
  EXIF_TAG_DOT_RANGE = 0x0150,
  EXIF_TAG_TARGET_PRINTER = 0x0151,
  EXIF_TAG_EXTRA_SAMPLES = 0x0152,
  EXIF_TAG_SAMPLE_FORMAT = 0x0153,
  EXIF_TAG_SMIN_SAMPLE_VALUE = 0x0154,
  EXIF_TAG_SMAX_SAMPLE_VALUE = 0x0155,
  EXIF_TAG_TRANSFER_RANGE = 0x0156,
  EXIF_TAG_CLIP_PATH = 0x0157,
  EXIF_TAG_X_CLIP_PATH_UNITS = 0x0158,
  EXIF_TAG_Y_CLIP_PATH_UNITS = 0x0159,
  EXIF_TAG_INDEXED = 0x015a,
  EXIF_TAG_JPEG_TABLES = 0x015b,
  EXIF_TAG_OPI_PROXY = 0x015f,
  EXIF_TAG_GLOBAL_PARAMETERS_IFD = 0x0190,
  EXIF_TAG_PROFILE_TYPE = 0x0191,
  EXIF_TAG_FAX_PROFILE = 0x0192,
  EXIF_TAG_CODING_METHODS = 0x0193,
  EXIF_TAG_VERSION_YEAR = 0x0194,
  EXIF_TAG_MODE_NUMBER = 0x0195,
  EXIF_TAG_DECODE = 0x01b1,
  EXIF_TAG_DEFAULT_IMAGE_COLOR = 0x01b2,
  EXIF_TAG_T82_OPTIONS = 0x01b3,
  EXIF_TAG_JPEG_TABLES2 = 0x01b5,
  EXIF_TAG_JPEG_PROC = 0x0200,
  EXIF_TAG_JPEG_INTERCHANGE_FORMAT = 0x0201,
  EXIF_TAG_JPEG_INTERCHANGE_FORMAT_LENGTH = 0x0202,
  EXIF_TAG_JPEG_RESTART_INTERVAL = 0x0203,
  EXIF_TAG_JPEG_LOSSLESS_PREDICTORS = 0x0205,
  EXIF_TAG_JPEG_POINT_TRANSFORMS = 0x0206,
  EXIF_TAG_JPEGQ_TABLES = 0x0207,
  EXIF_TAG_JPEGDC_TABLES = 0x0208,
  EXIF_TAG_JPEGAC_TABLES = 0x0209,
  EXIF_TAG_YCBCR_COEFFICIENTS = 0x0211,
  EXIF_TAG_YCBCR_SUB_SAMPLING = 0x0212,
  EXIF_TAG_YCBCR_POSITIONING = 0x0213,
  EXIF_TAG_REFERENCE_BLACK_WHITE = 0x0214,
  EXIF_TAG_STRIP_ROW_COUNTS = 0x022f,
  EXIF_TAG_XML_PACKET = 0x02bc,
  EXIF_TAG_USPTO_MISCELLANEOUS = 0x03e7,
  EXIF_TAG_RELATED_IMAGE_FILE_FORMAT = 0x1000,
  EXIF_TAG_RELATED_IMAGE_WIDTH = 0x1001,
  EXIF_TAG_RELATED_IMAGE_LENGTH = 0x1002,
  EXIF_TAG_RATING = 0x4746,
  EXIF_TAG_XP_DIP_XML = 0x4747,
  EXIF_TAG_STITCH_INFO = 0x4748,
  EXIF_TAG_RATING_PERCENT = 0x4749,
  EXIF_TAG_SONY_RAW_FILE_TYPE = 0x7000,
  EXIF_TAG_SONY_TONE_CURVE = 0x7010,
  EXIF_TAG_VIGNETTING_CORRECTION = 0x7031,
  EXIF_TAG_VIGNETTING_CORR_PARAMS = 0x7032,
  EXIF_TAG_CHROMATIC_ABERRATION_CORRECTION = 0x7034,
  EXIF_TAG_CHROMATIC_ABERRATION_CORR_PARAMS = 0x7035,
  EXIF_TAG_DISTORTION_CORRECTION = 0x7036,
  EXIF_TAG_DISTORTION_CORR_PARAMS = 0x7037,
  EXIF_TAG_SONY_CROP_TOP_LEFT = 0x74c7,
  EXIF_TAG_SONY_CROP_SIZE = 0x74c8,
  EXIF_TAG_IMAGE_ID = 0x800d,
  EXIF_TAG_WANG_TAG1 = 0x80a3,
  EXIF_TAG_WANG_ANNOTATION = 0x80a4,
  EXIF_TAG_WANG_TAG3 = 0x80a5,
  EXIF_TAG_WANG_TAG4 = 0x80a6,
  EXIF_TAG_IMAGE_REFERENCE_POINTS = 0x80b9,
  EXIF_TAG_REGION_XFORM_TACK_POINT = 0x80ba,
  EXIF_TAG_WARP_QUADRILATERAL = 0x80bb,
  EXIF_TAG_AFFINE_TRANSFORM_MAT = 0x80bc,
  EXIF_TAG_MATTEING = 0x80e3,
  EXIF_TAG_DATA_TYPE = 0x80e4,
  EXIF_TAG_IMAGE_DEPTH = 0x80e5,
  EXIF_TAG_TILE_DEPTH = 0x80e6,
  EXIF_TAG_IMAGE_FULL_WIDTH = 0x8214,
  EXIF_TAG_IMAGE_FULL_LENGTH = 0x8215,
  EXIF_TAG_TEXTURE_FORMAT = 0x8216,
  EXIF_TAG_WRAP_MODES = 0x8217,
  EXIF_TAG_FOV_COT = 0x8218,
  EXIF_TAG_MATRIX_WORLD_TO_SCREEN = 0x8219,
  EXIF_TAG_MATRIX_WORLD_TO_CAMERA = 0x821a,
  EXIF_TAG_MODEL2 = 0x827d,
  EXIF_TAG_CFA_REPEAT_PATTERN_DIM = 0x828d,
  EXIF_TAG_CFA_PATTERN = 0x828e,
  EXIF_TAG_BATTERY_LEVEL = 0x828f,
  EXIF_TAG_KODAK_IFD = 0x8290,
  EXIF_TAG_COPYRIGHT = 0x8298,
  EXIF_TAG_EXPOSURE_TIME = 0x829a,
  EXIF_TAG_FNUMBER = 0x829d,
  EXIF_TAG_MD_FILE_TAG = 0x82a5,
  EXIF_TAG_MD_SCALE_PIXEL = 0x82a6,
  EXIF_TAG_MD_COLOR_TABLE = 0x82a7,
  EXIF_TAG_MD_LAB_NAME = 0x82a8,
  EXIF_TAG_MD_SAMPLE_INFO = 0x82a9,
  EXIF_TAG_MD_PREP_DATE = 0x82aa,
  EXIF_TAG_MD_PREP_TIME = 0x82ab,
  EXIF_TAG_MD_FILE_UNITS = 0x82ac,
  EXIF_TAG_PIXEL_SCALE = 0x830e,
  EXIF_TAG_ADVENT_SCALE = 0x8335,
  EXIF_TAG_ADVENT_REVISION = 0x8336,
  EXIF_TAG_UIC1_TAG = 0x835c,
  EXIF_TAG_UIC2_TAG = 0x835d,
  EXIF_TAG_UIC3_TAG = 0x835e,
  EXIF_TAG_UIC4_TAG = 0x835f,
  EXIF_TAG_IPTC_NAA = 0x83bb,
  EXIF_TAG_INTERGRAPH_PACKET_DATA = 0x847e,
  EXIF_TAG_INTERGRAPH_FLAG_REGISTERS = 0x847f,
  EXIF_TAG_INTERGRAPH_MATRIX = 0x8480,
  EXIF_TAG_INGR_RESERVED = 0x8481,
  EXIF_TAG_MODEL_TIE_POINT = 0x8482,
  EXIF_TAG_SITE = 0x84e0,
  EXIF_TAG_COLOR_SEQUENCE = 0x84e1,
  EXIF_TAG_IT8_HEADER = 0x84e2,
  EXIF_TAG_RASTER_PADDING = 0x84e3,
  EXIF_TAG_BITS_PER_RUN_LENGTH = 0x84e4,
  EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH = 0x84e5,
  EXIF_TAG_COLOR_TABLE = 0x84e6,
  EXIF_TAG_IMAGE_COLOR_INDICATOR = 0x84e7,
  EXIF_TAG_BACKGROUND_COLOR_INDICATOR = 0x84e8,
  EXIF_TAG_IMAGE_COLOR_VALUE = 0x84e9,
  EXIF_TAG_BACKGROUND_COLOR_VALUE = 0x84ea,
  EXIF_TAG_PIXEL_INTENSITY_RANGE = 0x84eb,
  EXIF_TAG_TRANSPARENCY_INDICATOR = 0x84ec,
  EXIF_TAG_COLOR_CHARACTERIZATION = 0x84ed,
  EXIF_TAG_HC_USAGE = 0x84ee,
  EXIF_TAG_TRAP_INDICATOR = 0x84ef,
  EXIF_TAG_CMYK_EQUIVALENT = 0x84f0,
  EXIF_TAG_SEM_INFO = 0x8546,
  EXIF_TAG_AFCP_IPTC = 0x8568,
  EXIF_TAG_PIXEL_MAGIC_JBIG_OPTIONS = 0x85b8,
  EXIF_TAG_JPL_CARTO_IFD = 0x85d7,
  EXIF_TAG_MODEL_TRANSFORM = 0x85d8,
  EXIF_TAG_WB_GRGB_LEVELS = 0x8602,
  EXIF_TAG_LEAF_DATA = 0x8606,
  EXIF_TAG_IMAGE_RESOURCES = 0x8649,
  EXIF_TAG_EXIF_IFD_POINTER = 0x8769,
  EXIF_TAG_INTER_COLOR_PROFILE = 0x8773,
  EXIF_TAG_TIFF_FX_EXTENSIONS = 0x877f,
  EXIF_TAG_MULTI_PROFILES = 0x8780,
  EXIF_TAG_SHARED_DATA = 0x8781,
  EXIF_TAG_T88_OPTIONS = 0x8782,
  EXIF_TAG_IMAGE_LAYER = 0x87ac,
  EXIF_TAG_GEO_TIFF_DIRECTORY = 0x87af,
  EXIF_TAG_GEO_TIFF_DOUBLE_PARAMS = 0x87b0,
  EXIF_TAG_GEO_TIFF_ASCII_PARAMS = 0x87b1,
  EXIF_TAG_JBIG_OPTIONS = 0x87be,
  EXIF_TAG_EXPOSURE_PROGRAM = 0x8822,
  EXIF_TAG_SPECTRAL_SENSITIVITY = 0x8824,
  EXIF_TAG_GPS_INFO_IFD_POINTER = 0x8825,
  EXIF_TAG_ISO_SPEED_RATINGS = 0x8827,
  EXIF_TAG_OECF = 0x8828,
  EXIF_TAG_INTERLACE = 0x8829,
  EXIF_TAG_TIME_ZONE_OFFSET = 0x882a,
  EXIF_TAG_SELF_TIMER_MODE = 0x882b,
  EXIF_TAG_SENSITIVITY_TYPE = 0x8830,
  EXIF_TAG_STANDARD_OUTPUT_SENSITIVITY = 0x8831,
  EXIF_TAG_RECOMMENDED_EXPOSURE_INDEX = 0x8832,
  EXIF_TAG_ISO_SPEED = 0x8833,
  EXIF_TAG_ISO_SPEEDLatitudeYYY = 0x8834,
  EXIF_TAG_ISO_SPEEDLatitudeZZZ = 0x8835,
  EXIF_TAG_FAX_RECV_PARAMS = 0x885c,
  EXIF_TAG_FAX_SUB_ADDRESS = 0x885d,
  EXIF_TAG_FAX_RECV_TIME = 0x885e,
  EXIF_TAG_FEDEX_EDR = 0x8871,
  EXIF_TAG_LEAF_SUB_IFD = 0x888a,
  EXIF_TAG_EXIF_VERSION = 0x9000,
  EXIF_TAG_DATE_TIME_ORIGINAL = 0x9003,
  EXIF_TAG_DATE_TIME_DIGITIZED = 0x9004,
  EXIF_TAG_OFFSET_TIME = 0x9010,
  EXIF_TAG_OFFSET_TIME_ORIGINAL = 0x9011,
  EXIF_TAG_OFFSET_TIME_DIGITIZED = 0x9012,
  EXIF_TAG_COMPONENTS_CONFIGURATION = 0x9101,
  EXIF_TAG_COMPRESSED_BITS_PER_PIXEL = 0x9102,
  EXIF_TAG_SHUTTER_SPEED_VALUE = 0x9201,
  EXIF_TAG_APERTURE_VALUE = 0x9202,
  EXIF_TAG_BRIGHTNESS_VALUE = 0x9203,
  EXIF_TAG_EXPOSURE_BIAS_VALUE = 0x9204,
  EXIF_TAG_MAX_APERTURE_VALUE = 0x9205,
  EXIF_TAG_SUBJECT_DISTANCE = 0x9206,
  EXIF_TAG_METERING_MODE = 0x9207,
  EXIF_TAG_LIGHT_SOURCE = 0x9208,
  EXIF_TAG_FLASH = 0x9209,
  EXIF_TAG_FOCAL_LENGTH = 0x920a,
  EXIF_TAG_FLASH_ENERGY2 = 0x920b,
  EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE2 = 0x920c,
  EXIF_TAG_NOISE = 0x920d,
  EXIF_TAG_FOCAL_PLANE_X_RESOLUTION2 = 0x920e,
  EXIF_TAG_FOCAL_PLANE_Y_RESOLUTION2 = 0x920f,
  EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT2 = 0x9210,
  EXIF_TAG_IMAGE_NUMBER = 0x9211,
  EXIF_TAG_SECURITY_CLASSIFICATION = 0x9212,
  EXIF_TAG_IMAGE_HISTORY = 0x9213,
  EXIF_TAG_SUBJECT_AREA = 0x9214,
  EXIF_TAG_EXPOSURE_INDEX2 = 0x9215,
  EXIF_TAG_TIFF_EP_STANDARD_ID = 0x9216,
  EXIF_TAG_SENSING_METHOD2 = 0x9217,
  EXIF_TAG_CIP3_DATA_FILE = 0x923a,
  EXIF_TAG_CIP3_SHEET = 0x923b,
  EXIF_TAG_CIP3_SIDE = 0x923c,
  EXIF_TAG_STO_NITS = 0x923f,
  EXIF_TAG_MAKER_NOTE = 0x927c,
  EXIF_TAG_USER_COMMENT = 0x9286,
  EXIF_TAG_SUB_SEC_TIME = 0x9290,
  EXIF_TAG_SUB_SEC_TIME_ORIGINAL = 0x9291,
  EXIF_TAG_SUB_SEC_TIME_DIGITIZED = 0x9292,
  EXIF_TAG_MS_DOCUMENT_TEXT = 0x932f,
  EXIF_TAG_MS_PROPERTY_SET_STORAGE = 0x9330,
  EXIF_TAG_MS_DOCUMENT_TEXT_POSITION = 0x9331,
  EXIF_TAG_IMAGE_SOURCE_DATA = 0x935c,
  EXIF_TAG_AMBIENT_TEMPERATURE = 0x9400,
  EXIF_TAG_HUMIDITY = 0x9401,
  EXIF_TAG_PRESSURE = 0x9402,
  EXIF_TAG_WATER_DEPTH = 0x9403,
  EXIF_TAG_ACCELERATION = 0x9404,
  EXIF_TAG_CAMERA_ELEVATION_ANGLE = 0x9405,
  EXIF_TAG_XP_TITLE = 0x9c9b,
  EXIF_TAG_XP_COMMENT = 0x9c9c,
  EXIF_TAG_XP_AUTHOR = 0x9c9d,
  EXIF_TAG_XP_KEYWORDS = 0x9c9e,
  EXIF_TAG_XP_SUBJECT = 0x9c9f,
  EXIF_TAG_FLASH_PIX_VERSION = 0xa000,
  EXIF_TAG_COLOR_SPACE = 0xa001,
  EXIF_TAG_PIXEL_X_DIMENSION = 0xa002,
  EXIF_TAG_PIXEL_Y_DIMENSION = 0xa003,
  EXIF_TAG_RELATED_SOUND_FILE = 0xa004,
  EXIF_TAG_INTEROPERABILITY_IFD_POINTER = 0xa005,
  EXIF_TAG_SAMSUNG_RAW_POINTERS_OFFSET = 0xa010,
  EXIF_TAG_SAMSUNG_RAW_POINTERS_LENGTH = 0xa011,
  EXIF_TAG_SAMSUNG_RAW_BYTE_ORDER = 0xa101,
  EXIF_TAG_SAMSUNG_RAW_UNKNOWN = 0xa102,
  EXIF_TAG_FLASH_ENERGY = 0xa20b,
  EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE = 0xa20c,
  EXIF_TAG_FOCAL_PLANE_X_RESOLUTION = 0xa20e,
  EXIF_TAG_FOCAL_PLANE_Y_RESOLUTION = 0xa20f,
  EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT = 0xa210,
  EXIF_TAG_IMAGE_NUMBER2 = 0xa211,
  EXIF_TAG_SECURITY_CLASSIFICATION2 = 0xa212,
  EXIF_TAG_IMAGE_HISTORY2 = 0xa213,
  EXIF_TAG_SUBJECT_LOCATION = 0xa214,
  EXIF_TAG_EXPOSURE_INDEX = 0xa215,
  EXIF_TAG_TIFF_EP_STANDARD_ID2 = 0xa216,
  EXIF_TAG_SENSING_METHOD = 0xa217,
  EXIF_TAG_FILE_SOURCE = 0xa300,
  EXIF_TAG_SCENE_TYPE = 0xa301,
  EXIF_TAG_NEW_CFA_PATTERN = 0xa302,
  EXIF_TAG_CUSTOM_RENDERED = 0xa401,
  EXIF_TAG_EXPOSURE_MODE = 0xa402,
  EXIF_TAG_WHITE_BALANCE = 0xa403,
  EXIF_TAG_DIGITAL_ZOOM_RATIO = 0xa404,
  EXIF_TAG_FOCAL_LENGTH_IN_35MM_FILM = 0xa405,
  EXIF_TAG_SCENE_CAPTURE_TYPE = 0xa406,
  EXIF_TAG_GAIN_CONTROL = 0xa407,
  EXIF_TAG_CONTRAST = 0xa408,
  EXIF_TAG_SATURATION = 0xa409,
  EXIF_TAG_SHARPNESS = 0xa40a,
  EXIF_TAG_DEVICE_SETTING_DESCRIPTION = 0xa40b,
  EXIF_TAG_SUBJECT_DISTANCE_RANGE = 0xa40c,
  EXIF_TAG_IMAGE_UNIQUE_ID = 0xa420,
  EXIF_TAG_CAMERA_OWNER_NAME = 0xa430,
  EXIF_TAG_BODY_SERIAL_NUMBER = 0xa431,
  EXIF_TAG_LENS_SPECIFICATION = 0xa432,
  EXIF_TAG_LENS_MAKE = 0xa433,
  EXIF_TAG_LENS_MODEL = 0xa434,
  EXIF_TAG_LENS_SERIAL_NUMBER = 0xa435,
  EXIF_TAG_COMPOSITE_IMAGE = 0xa460,
  EXIF_TAG_SOURCE_IMAGE_NUMBER_OF_COMPOSITE_IMAGE = 0xa461,
  EXIF_TAG_SOURCE_EXPOSURE_TIMES_OF_COMPOSITE_IMAGE = 0xa462,
  EXIF_TAG_GDAL_METADATA = 0xa480,
  EXIF_TAG_GDAL_NODATA = 0xa481,
  EXIF_TAG_GAMMA = 0xa500,
  EXIF_TAG_EXPAND_SOFTWARE = 0xafc0,
  EXIF_TAG_EXPAND_LENS = 0xafc1,
  EXIF_TAG_EXPAND_FILM = 0xafc2,
  EXIF_TAG_EXPAND_FILTER_LENS = 0xafc3,
  EXIF_TAG_EXPAND_SCANNER = 0xafc4,
  EXIF_TAG_EXPAND_FLASH_LAMP = 0xafc5,
  EXIF_TAG_HASSELBLAD_RAW_IMAGE = 0xb4c3,
  EXIF_TAG_PIXEL_FORMAT = 0xbc01,
  EXIF_TAG_TRANSFORMATION = 0xbc02,
  EXIF_TAG_UNCOMPRESSED = 0xbc03,
  EXIF_TAG_IMAGE_TYPE = 0xbc04,
  EXIF_TAG_IMAGE_WIDTH2 = 0xbc80,
  EXIF_TAG_IMAGE_HEIGHT2 = 0xbc81,
  EXIF_TAG_WIDTH_RESOLUTION = 0xbc82,
  EXIF_TAG_HEIGHT_RESOLUTION = 0xbc83,
  EXIF_TAG_IMAGE_OFFSET = 0xbcc0,
  EXIF_TAG_IMAGE_BYTE_COUNT = 0xbcc1,
  EXIF_TAG_ALPHA_OFFSET = 0xbcc2,
  EXIF_TAG_ALPHA_BYTE_COUNT = 0xbcc3,
  EXIF_TAG_IMAGE_DATA_DISCARD = 0xbcc4,
  EXIF_TAG_ALPHA_DATA_DISCARD = 0xbcc5,
  EXIF_TAG_OCE_SCANJOB_DESC = 0xc427,
  EXIF_TAG_OCE_APPLICATION_SELECTOR = 0xc428,
  EXIF_TAG_OCE_ID_NUMBER = 0xc429,
  EXIF_TAG_OCE_IMAGE_LOGIC = 0xc42a,
  EXIF_TAG_ANNOTATIONS = 0xc44f,
  EXIF_TAG_PRINT_IMAGE_MATCHING = 0xc4a5,
  EXIF_TAG_HASSELBLAD_EXIF = 0xc51b,
  EXIF_TAG_ORIGINAL_FILENAME = 0xc573,
  EXIF_TAG_USPTO_ORIGINAL_CONTENT_TYPE = 0xc580,
  EXIF_TAG_CR2_CFA_PATTERN = 0xc5e0,
  EXIF_TAG_DNG_VERSION = 0xc612,
  EXIF_TAG_DNG_BACKWARD_VERSION = 0xc613,
  EXIF_TAG_UNIQUE_CAMERA_MODEL = 0xc614,
  EXIF_TAG_LOCALIZED_CAMERA_MODEL = 0xc615,
  EXIF_TAG_CFA_PLANE_COLOR = 0xc616,
  EXIF_TAG_CFA_LAYOUT = 0xc617,
  EXIF_TAG_LINEARIZATION_TABLE = 0xc618,
  EXIF_TAG_BLACK_LEVEL_REPEAT_DIM = 0xc619,
  EXIF_TAG_BLACK_LEVEL = 0xc61a,
  EXIF_TAG_BLACK_LEVEL_DELTA_H = 0xc61b,
  EXIF_TAG_BLACK_LEVEL_DELTA_V = 0xc61c,
  EXIF_TAG_WHITE_LEVEL = 0xc61d,
  EXIF_TAG_DEFAULT_SCALE = 0xc61e,
  EXIF_TAG_DEFAULT_CROP_ORIGIN = 0xc61f,
  EXIF_TAG_DEFAULT_CROP_SIZE = 0xc620,
  EXIF_TAG_COLOR_MATRIX1 = 0xc621,
  EXIF_TAG_COLOR_MATRIX2 = 0xc622,
  EXIF_TAG_CAMERA_CALIBRATION1 = 0xc623,
  EXIF_TAG_CAMERA_CALIBRATION2 = 0xc624,
  EXIF_TAG_REDUCTION_MATRIX1 = 0xc625,
  EXIF_TAG_REDUCTION_MATRIX2 = 0xc626,
  EXIF_TAG_ANALOG_BALANCE = 0xc627,
  EXIF_TAG_AS_SHOT_NEUTRAL = 0xc628,
  EXIF_TAG_AS_SHOT_WHITE_XY = 0xc629,
  EXIF_TAG_BASELINE_EXPOSURE = 0xc62a,
  EXIF_TAG_BASELINE_NOISE = 0xc62b,
  EXIF_TAG_BASELINE_SHARPNESS = 0xc62c,
  EXIF_TAG_BAYER_GREEN_SPLIT = 0xc62d,
  EXIF_TAG_LINEAR_RESPONSE_LIMIT = 0xc62e,
  EXIF_TAG_CAMERA_SERIAL_NUMBER = 0xc62f,
  EXIF_TAG_DNG_LENS_INFO = 0xc630,
  EXIF_TAG_CHROMA_BLUR_RADIUS = 0xc631,
  EXIF_TAG_ANTI_ALIAS_STRENGTH = 0xc632,
  EXIF_TAG_SHADOW_SCALE = 0xc633,
  EXIF_TAG_DNG_PRIVATE_DATA = 0xc634,
  EXIF_TAG_MAKER_NOTE_SAFETY = 0xc635,
  EXIF_TAG_RAW_IMAGE_SEGMENTATION = 0xc640,
  EXIF_TAG_CALIBRATION_ILLUMINANT1 = 0xc65a,
  EXIF_TAG_CALIBRATION_ILLUMINANT2 = 0xc65b,
  EXIF_TAG_BEST_QUALITY_SCALE = 0xc65c,
  EXIF_TAG_RAW_DATA_UNIQUE_ID = 0xc65d,
  EXIF_TAG_ALIAS_LAYER_METADATA = 0xc660,
  EXIF_TAG_ORIGINAL_RAW_FILE_NAME = 0xc68b,
  EXIF_TAG_ORIGINAL_RAW_FILE_DATA = 0xc68c,
  EXIF_TAG_ACTIVE_AREA = 0xc68d,
  EXIF_TAG_MASKED_AREAS = 0xc68e,
  EXIF_TAG_AS_SHOT_ICC_PROFILE = 0xc68f,
  EXIF_TAG_AS_SHOT_PRE_PROFILE_MATRIX = 0xc690,
  EXIF_TAG_CURRENT_ICC_PROFILE = 0xc691,
  EXIF_TAG_CURRENT_PRE_PROFILE_MATRIX = 0xc692,
  EXIF_TAG_COLORIMETRIC_REFERENCE = 0xc6bf,
  EXIF_TAG_S_RAW_TYPE = 0xc6c5,
  EXIF_TAG_PANASONIC_TITLE = 0xc6d2,
  EXIF_TAG_PANASONIC_TITLE2 = 0xc6d3,
  EXIF_TAG_CAMERA_CALIBRATION_SIG = 0xc6f3,
  EXIF_TAG_PROFILE_CALIBRATION_SIG = 0xc6f4,
  EXIF_TAG_PROFILE_IFD = 0xc6f5,
  EXIF_TAG_AS_SHOT_PROFILE_NAME = 0xc6f6,
  EXIF_TAG_NOISE_REDUCTION_APPLIED = 0xc6f7,
  EXIF_TAG_PROFILE_NAME = 0xc6f8,
  EXIF_TAG_PROFILE_HUE_SAT_MAP_DIMS = 0xc6f9,
  EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA1 = 0xc6fa,
  EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA2 = 0xc6fb,
  EXIF_TAG_PROFILE_TONE_CURVE = 0xc6fc,
  EXIF_TAG_PROFILE_EMBED_POLICY = 0xc6fd,
  EXIF_TAG_PROFILE_COPYRIGHT = 0xc6fe,
  EXIF_TAG_FORWARD_MATRIX1 = 0xc714,
  EXIF_TAG_FORWARD_MATRIX2 = 0xc715,
  EXIF_TAG_PREVIEW_APPLICATION_NAME = 0xc716,
  EXIF_TAG_PREVIEW_APPLICATION_VERSION = 0xc717,
  EXIF_TAG_PREVIEW_SETTINGS_NAME = 0xc718,
  EXIF_TAG_PREVIEW_SETTINGS_DIGEST = 0xc719,
  EXIF_TAG_PREVIEW_COLOR_SPACE = 0xc71a,
  EXIF_TAG_PREVIEW_DATE_TIME = 0xc71b,
  EXIF_TAG_RAW_IMAGE_DIGEST = 0xc71c,
  EXIF_TAG_ORIGINAL_RAW_FILE_DIGEST = 0xc71d,
  EXIF_TAG_SUB_TILE_BLOCK_SIZE = 0xc71e,
  EXIF_TAG_ROW_INTERLEAVE_FACTOR = 0xc71f,
  EXIF_TAG_PROFILE_LOOK_TABLE_DIMS = 0xc725,
  EXIF_TAG_PROFILE_LOOK_TABLE_DATA = 0xc726,
  EXIF_TAG_OPCODE_LIST1 = 0xc740,
  EXIF_TAG_OPCODE_LIST2 = 0xc741,
  EXIF_TAG_OPCODE_LIST3 = 0xc74e,
  EXIF_TAG_NOISE_PROFILE = 0xc761,
  EXIF_TAG_TIME_CODES = 0xc763,
  EXIF_TAG_FRAME_RATE = 0xc764,
  EXIF_TAG_T_STOP = 0xc772,
  EXIF_TAG_REEL_NAME = 0xc789,
  EXIF_TAG_ORIGINAL_DEFAULT_FINAL_SIZE = 0xc791,
  EXIF_TAG_ORIGINAL_BEST_QUALITY_SIZE = 0xc792,
  EXIF_TAG_ORIGINAL_DEFAULT_CROP_SIZE = 0xc793,
  EXIF_TAG_CAMERA_LABEL = 0xc7a1,
  EXIF_TAG_PROFILE_HUE_SAT_MAP_ENCODING = 0xc7a3,
  EXIF_TAG_PROFILE_LOOK_TABLE_ENCODING = 0xc7a4,
  EXIF_TAG_BASELINE_EXPOSURE_OFFSET = 0xc7a5,
  EXIF_TAG_DEFAULT_BLACK_RENDER = 0xc7a6,
  EXIF_TAG_NEW_RAW_IMAGE_DIGEST = 0xc7a7,
  EXIF_TAG_RAW_TO_PREVIEW_GAIN = 0xc7a8,
  EXIF_TAG_CACHE_VERSION = 0xc7aa,
  EXIF_TAG_DEFAULT_USER_CROP = 0xc7b5,
  EXIF_TAG_NIKON_NEF_INFO = 0xc7d5,
  EXIF_TAG_DEPTH_FORMAT = 0xc7e9,
  EXIF_TAG_DEPTH_NEAR = 0xc7ea,
  EXIF_TAG_DEPTH_FAR = 0xc7eb,
  EXIF_TAG_DEPTH_UNITS = 0xc7ec,
  EXIF_TAG_DEPTH_MEASURE_TYPE = 0xc7ed,
  EXIF_TAG_DEPTH_ENHANCE_PARAMS = 0xc7ee,
  EXIF_TAG_PROFILE_GAIN_TABLE_MAP = 0xcd2d,
  EXIF_TAG_SEMANTIC_NAME = 0xcd2e,
  EXIF_TAG_SEMANTIC_INSTANCE_ID = 0xcd30,
  EXIF_TAG_CALIBRATION_ILLUMINANT3 = 0xcd31,
  EXIF_TAG_CAMERA_CALIBRATION3 = 0xcd32,
  EXIF_TAG_COLOR_MATRIX3 = 0xcd33,
  EXIF_TAG_FORWARD_MATRIX3 = 0xcd34,
  EXIF_TAG_ILLUMINANT_DATA1 = 0xcd35,
  EXIF_TAG_ILLUMINANT_DATA2 = 0xcd36,
  EXIF_TAG_ILLUMINANT_DATA3 = 0xcd37,
  EXIF_TAG_MASK_SUB_AREA = 0xcd38,
  EXIF_TAG_PROFILE_HUE_SAT_MAP_DATA3 = 0xcd39,
  EXIF_TAG_REDUCTION_MATRIX3 = 0xcd3a,
  EXIF_TAG_RGB_TABLES = 0xcd3b,
  EXIF_TAG_PADDING = 0xea1c,
  EXIF_TAG_OFFSET_SCHEMA = 0xea1d,
  EXIF_TAG_CAMERA_OWNER_NAME2 = 0xfde8,
  EXIF_TAG_CAMERA_SERIAL_NUMBER2 = 0xfde9,
  EXIF_TAG_LENS = 0xfdea,
  EXIF_TAG_KDC_IFD = 0xfe00,
  EXIF_TAG_RAW_FILE = 0xfe4c,
  EXIF_TAG_CONVERTER = 0xfe4d,
  EXIF_TAG_WHITE_BALANCE2 = 0xfe4e,
  EXIF_TAG_EXPOSURE = 0xfe51,
  EXIF_TAG_SHADOWS = 0xfe52,
  EXIF_TAG_BRIGHTNESS = 0xfe53,
  EXIF_TAG_CONTRAST2 = 0xfe54,
  EXIF_TAG_SATURATION2 = 0xfe55,
  EXIF_TAG_SHARPNESS2 = 0xfe56,
  EXIF_TAG_SMOOTHNESS = 0xfe57,
  EXIF_TAG_MOIRE_FILTER = 0xfe58,
} ExifTag;

/* GPS tags overlap with above ones. */
#define EXIF_TAG_GPS_VERSION_ID        0x0000
#define EXIF_TAG_GPS_LATITUDE_REF      0x0001 /* INTEROPERABILITY_INDEX   */
#define EXIF_TAG_GPS_LATITUDE          0x0002 /* INTEROPERABILITY_VERSION */
#define EXIF_TAG_GPS_LONGITUDE_REF     0x0003
#define EXIF_TAG_GPS_LONGITUDE         0x0004
#define EXIF_TAG_GPS_ALTITUDE_REF      0x0005
#define EXIF_TAG_GPS_ALTITUDE          0x0006
#define EXIF_TAG_GPS_TIME_STAMP        0x0007
#define EXIF_TAG_GPS_SATELLITES        0x0008
#define EXIF_TAG_GPS_STATUS            0x0009
#define EXIF_TAG_GPS_MEASURE_MODE      0x000a
#define EXIF_TAG_GPS_DOP               0x000b
#define EXIF_TAG_GPS_SPEED_REF         0x000c
#define EXIF_TAG_GPS_SPEED             0x000d
#define EXIF_TAG_GPS_TRACK_REF         0x000e
#define EXIF_TAG_GPS_TRACK             0x000f
#define EXIF_TAG_GPS_IMG_DIRECTION_REF 0x0010
#define EXIF_TAG_GPS_IMG_DIRECTION     0x0011
#define EXIF_TAG_GPS_MAP_DATUM         0x0012
#define EXIF_TAG_GPS_DEST_LATITUDE_REF 0x0013
#define EXIF_TAG_GPS_DEST_LATITUDE     0x0014
#define EXIF_TAG_GPS_DEST_LONGITUDE_REF 0x0015
#define EXIF_TAG_GPS_DEST_LONGITUDE     0x0016
#define EXIF_TAG_GPS_DEST_BEARING_REF   0x0017
#define EXIF_TAG_GPS_DEST_BEARING       0x0018
#define EXIF_TAG_GPS_DEST_DISTANCE_REF  0x0019
#define EXIF_TAG_GPS_DEST_DISTANCE      0x001a
#define EXIF_TAG_GPS_PROCESSING_METHOD  0x001b
#define EXIF_TAG_GPS_AREA_INFORMATION   0x001c
#define EXIF_TAG_GPS_DATE_STAMP         0x001d
#define EXIF_TAG_GPS_DIFFERENTIAL       0x001e
#define EXIF_TAG_GPS_H_POSITIONING_ERROR 0x001f

/*! What level of support a tag enjoys in the EXIF standard */
typedef enum {
	/*! The meaning of this tag is unknown */
	EXIF_SUPPORT_LEVEL_UNKNOWN = 0,

	/*! This tag is not allowed in the given IFD */
	EXIF_SUPPORT_LEVEL_NOT_RECORDED,

	/*! This tag is mandatory in the given IFD */
	EXIF_SUPPORT_LEVEL_MANDATORY,

	/*! This tag is optional in the given IFD */
	EXIF_SUPPORT_LEVEL_OPTIONAL
} ExifSupportLevel;

/*! Return the tag ID given its unique textual name.
 *
 * \param[in] name tag name
 * \return tag ID, or 0 if tag not found
 * \note The tag not found value cannot be distinguished from a legitimate
 *   tag number 0.
 */
ExifTag          exif_tag_from_name                (const char *name);

/*! Return a textual name of the given tag when found in the given IFD. The
 * name is a short, unique, non-localized text string containing only
 * US-ASCII alphanumeric characters.
 *
 * \param[in] tag EXIF tag
 * \param[in] ifd IFD
 * \return textual name of the tag, or NULL if the tag is unknown
 */
const char      *exif_tag_get_name_in_ifd          (ExifTag tag, ExifIfd ifd);

/*! Return a textual title of the given tag when found in the given IFD.
 * The title is a short, localized description of the tag.
 *
 * \param[in] tag EXIF tag
 * \param[in] ifd IFD
 * \return textual title of the tag, or NULL if the tag is unknown
 */
const char      *exif_tag_get_title_in_ifd         (ExifTag tag, ExifIfd ifd);

/*! Return a verbose textual description of the given tag when found in the
 * given IFD. The description is a verbose, localized description of the tag.
 *
 * \param[in] tag EXIF tag
 * \param[in] ifd IFD
 * \return textual description of the tag, or NULL if the tag is unknown
 */
const char      *exif_tag_get_description_in_ifd   (ExifTag tag, ExifIfd ifd);

/*! Return whether the given tag is mandatory or not in the given IFD and
 * data type according to the EXIF specification. If the IFD given is
 * EXIF_IFD_COUNT, the result is EXIF_SUPPORT_LEVEL_UNKNOWN. If the data
 * type is EXIF_DATA_TYPE_UNKNOWN, the result is
 * EXIF_SUPPORT_LEVEL_UNKNOWN unless the support level is the same for
 * all data types.
 *
 * \param[in] tag EXIF tag
 * \param[in] ifd IFD or EXIF_IFD_COUNT
 * \param[in] t data type or EXIF_DATA_TYPE_UNKNOWN
 * \return the level of support for this tag
 */
ExifSupportLevel exif_tag_get_support_level_in_ifd (ExifTag tag, ExifIfd ifd,
                                                    ExifDataType t);

/* Don't use these functions. They are here for compatibility only. */

/*! \deprecated Use #exif_tag_get_name_in_ifd instead */
const char     *exif_tag_get_name        (ExifTag tag);

/*! \deprecated Use #exif_tag_get_title_in_ifd instead */
const char     *exif_tag_get_title       (ExifTag tag);

/*! \deprecated Use #exif_tag_get_description_in_ifd instead */
const char     *exif_tag_get_description (ExifTag tag);


/* For now, do not use these functions. */

/*! \internal */
ExifTag      exif_tag_table_get_tag  (unsigned int n);

/*! \internal */
const char  *exif_tag_table_get_name (unsigned int n);

/*! \internal */
unsigned int exif_tag_table_count    (void);


/* Don't use these definitions. They are here for compatibility only. */

/*! \deprecated Use EXIF_TAG_PRINT_IMAGE_MATCHING instead. */
#define EXIF_TAG_UNKNOWN_C4A5 EXIF_TAG_PRINT_IMAGE_MATCHING

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* !defined(LIBEXIF_EXIF_TAG_H) */
